import Head from "next/head";
import Banner from './Banner'
const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Moos -meet your cravings</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="bg-white  relative">
				<div className="md:max-w-7xl w-full mx-auto  h-[80px]  ">
                   <div className="absolute  bg-black  text-center w-[300px] z-0">
                   <h1 className="text-white text-lg uppercase font-bold h-[350px] mt-[10px]">Moos</h1>
                   </div>
                   {/* navbar */}
					<nav className="flex w-full justify-end items-center  h-16">
						<ul className="flex gap-4">
							<li>Home</li>
							<li>Orders</li>
							<li>Products</li>
							<li>Contact</li>
						</ul>
					</nav>
				</div>
			</header>
           
			<main>{children}</main>
			<footer></footer>
		</>
	);
};

export default Layout;
